### ISSUE TITLE
Update README and build scripts for successful build on mac os x

### ISSUE THREAD

**Issue by PMSeitzer** [ElucidataInc/ElMaven#1002]
**Describe the bug**
Unable to build on Mac OS X following instructions in README

**To Reproduce**
Follow the instructions in the current README on a mac os x Version 10.14.3
Running 'make' does not complete successfully (errors out)

**Expected behavior**
running 'make' should complete successfully

**Screenshots**

**System (please complete the following information):**
Mac OS x Version 10.14.3

**Additional context**

**Comment by PMSeitzer** [comment]
If possible, I would like to work on this issue, please assign it to me.

**Comment by rish9511** [comment]
@PMSeitzer 

We recently changed our build scripts to look for a specific version  of clang when compiling on macOS. This change worked on few systems but did not work on others. Commit e3bac9c021b981f14b578a8e2f5e8a650cd456af fixed this issue. It required fixing in just the build scripts and not in README.  If the error looks something like 'Unable to find clang', then please use the latest develop, if you are not using it already, as it has the fix for this

If you are already using latest develop, then please let us know the error you are facing, either in the original issue or as a separate comment. Also let us know if you need any help fixing the issue :)

**Comment by shubhra-agrawal** [comment]
@PMSeitzer This issue seems to be fixed. Now you can build El-MAVEN on Mac using QtCreator as well, as requested. Closing this thread
