### ISSUE TITLE
Uploading mzroll is not multi-processed

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#11]
Uploading the mzXml files takes use of all the processors but loading via mzroll only 1 core is being used.

**Comment by chubukov** [comment]
@sahil21 @shubhra-agrawal I'm curious if this could be revived. I remember there were some major technical hurdles on the last attempt, but I'm wondering if after some of the refactoring you've done it might be easier. I thought I remembered seeing it on some of the sprints.

This issue is probably the main reason I personally rarely use mzroll.

**Comment by shubhra-agrawal** [comment]
@chubukov We ran into a lot of problems while multiprocessing mzroll because samples are parsed serially at the moment. Once we change the way samples are parsed, this shouldn't be a challenge. I'll see if this can be included in the next release and let you know.

**Comment by saifulbkhan** [comment]
We do not plan on adding new features to or maintain the mzroll format. emDB files are now the preferred way of saving/restoring sessions. And they support multi-processed sample loading.
