### ISSUE TITLE
Retention time for Bruker Files is displayed in EIC in seconds instead of minutes.

### ISSUE THREAD

**Issue by shefalilathwal** [ElucidataInc/ElMaven#1176]
I have files from a Bruker Instrument. I converted them to .mzML format using MSconvert. The file conversion happens correctly and the files are read by EL-MAVEN. However, the retention time axis appears in seconds instead of minutes. This issue is creating problems because downstream in PollyPhi (since the PollyPhi app displays a fixed rt window around the peaks assuming that the rt is in minutes. So for these files, the peak appears very zoomed in and looks like noise. Additionally, for targeted analysis, the retention time reported for metabolites is in minutes, so thinking in seconds is non-intuitive during usage.

Link to the files: shared over email.

**Comment by saifulbkhan** [comment]
The seconds in place of minutes issue happens because El-MAVEN has until now been assuming that all scan retention times are recorded (or at least converted) in terms of minutes only. There is no check for what is the unit of time (even though it is available in the mzML files). The files in consideration here, store their scan RT values in seconds but El-MAVEN naively shows them exactly as they are on the RT axis which has always been a measure of minutes.

We will correct this in our upcoming v0.10.0 release, which is expected to be available by January 2020.

**Comment by shefalilathwal** [comment]
Hi Saiful, Can you describe how the files will work after the fix? What should I expect to see in the EIC now in El-MAVEN after I import these files? Earlier because of this issue, I had to give the rt in my compound database in seconds. After the fix, will I now give the rt in my compound database in minutes?

**Comment by saifulbkhan** [comment]
@shefalilathwal Almost all modules in El-MAVEN assume that they will only ever have to deal with RT in minutes. And that is why, with this fix, we will convert all RT from seconds to minutes for convenience. This is also something that users have come to expect and we do not intend to make them worry about unit conversion too much. Therefore, after this fix, El-MAVEN will display EICs for your samples the same as it does for any other dataset. This means, you should provide expected metabolite RT values as minutes, in your database. There should not be any unexpected changes to your workflow, either.

Let me know if you have any other questions.

**Comment by shefalilathwal** [comment]
@saifulbkhan Got it. Thank you for the detailed explanation!

**Comment by saifulbkhan** [comment]
@shefalilathwal This error has been fixed and should not be present in the latest release - v0.10.0.
