### ISSUE TITLE
Logging feature

### ISSUE THREAD

**Issue by GeorgeSabu** [ElucidataInc/ElMaven#132]
User interaction has to be logged.

**Comment by chubukov** [comment]
@sahil21 Not sure what the status of this is, or if it requires something from our end.

**Comment by sahil21** [comment]
@chubukov A library named "libplog" has been added to take care of logging in the application. We have not covered all the user interactions but most of them are covered. This log is sent to S3 when El-Maven crashes and the user selects "Send Report and Restart". But to enable sending, the user has to enter AWS s3 bucket credentials during the start of El-Maven (It is a one time procedure).

**Comment by chubukov** [comment]
Ok so I should just set up an s3 bucket and start using this, right? Sorry, I thought this was still a work in progress.

**Comment by sahil21** [comment]
Yes. You just have to create a S3 bucket and put the credentials there on
El-Maven. Also, the feedback button on bottom right also puts the feedback
message inside S3 bucket.

On 01-Aug-2017 6:17 PM, "Victor Chubukov" <notifications@github.com> wrote:

Ok so I should just set up an s3 bucket and start using this, right? Sorry,
I thought this was still a work in progress.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ElucidataInc/ElMaven/issues/132#issuecomment-319359907>,
or mute the thread
