### ISSUE TITLE
Limiting number of groups/compounds

### ISSUE THREAD

**Issue by pirman12** [ElucidataInc/ElMaven#1405]
I'm trying to keep this value at 1 when using the automated peak picking feature, but I keep getting numerous bookmarked rows for each metabolite.  

**To Reproduce**
1. Go to 'peak detection'
2. Click on 'limit number of groups per compound-->change to 1'
3. Still getting numerous peaks in the book mark for each metabolites
**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu, MacOS]
 - Version [e.g. v0.3.1]

**Additional context**

![image](https://user-images.githubusercontent.com/26168001/117696933-dfe99900-b18f-11eb-8b3d-b251238dac52.png)

**Comment by pirman12** [comment]
I realized this was due to not having RT inputted into the imported compound list.

**Comment by saif-el** [comment]
@pirman12 You can also limit the detection to only pick the most-suitable group per compound by setting this value to "1 best":

<img width="892" alt="Screenshot 2021-05-11 at 7 32 45 AM" src="https://user-images.githubusercontent.com/77447361/117747234-63a49380-b22b-11eb-8d10-2ec43027e5b2.png">

This feature still relies on you having provided RT for good results. Otherwise, it will choose the peak-group with the highest quality and intensity for that compound's m/z.
