### ISSUE TITLE
save project should either save all peak tables or be disabled

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#149]
There is a "save project" button on the samples widget. I believe that this saves the bookmarks table. This is actually quite confusing -- a user today assumed (reasonably enough) that it would save all the peak tables. 

I believe there is currently no functionality for an mzroll to contain multiple peak tables (correct?). In that case I vote for removing this button.

At some point we should talk about more intuitive button images on the peak table.

**Comment by chubukov** [comment]
@GeorgeSabu Actually, how does the new "recreate the entire state" feature deal with multiple tables? Could that be co-opted?

**Comment by chubukov** [comment]
A related question: it is currently not possible to load more than one peak table from mzroll files ( they go into bookmarks table). Does the new autosave version also address this?

**Comment by lparsons** [comment]
Perhaps a way to save/load peak tables independent of the project?

**Comment by saifulbkhan** [comment]
With release v0.6.1 we have started providing an option to save in a SQLite database file, with our custom extension ".emDB". A timestamped autosave file is also generated whenever the user curates a peakgroup (bookmark and mark good/bad) and keeps saving in it for any further curations. This file will be deleted if the user chooses to explicitly save a file for the session or chooses to exit without saving at all. Hopefully this new mechanism will help resolve some of the issues discussed in this thread.

The "Save Peaks" button has been removed from peak tables, since data necessary to recreate all peak tables in a session will be saved in emDB files.

The legacy "mzroll" format should be considered deprecated. Users should refrain from using it since it will be removed in a later release.

**Comment by saifulbkhan** [comment]
We have not decided yet on any particular release we plan to drop support for `.mzroll` files but we can allow loading them for a few more releases without the need for extra maintenance.

I agree that we should have proper documentation around which formats are supported or deprecated and to what extent. Regarding documentation for the new format, we will cover it more thoroughly as we approach our goal of being able to save the entire session state (not just data but settings as well) in `.emDB` (or maybe a backward-compatible successor of it). Until we have proper documentation for this available, you can find a list of current facilities provided by `.emDB`  in this [comment](https://github.com/ElucidataInc/ElMaven/pull/921#issuecomment-441930366).
