### ISSUE TITLE
EIC extraction when there are multiple peaks in the mass window

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#187]
This hasn't been a big issue because in most cases there is no effect, but I believe there is a fundamental flaw in the way that Maven calculates the EIC.

If a scan (i.e. one point along the time axis) contains readings for multiple m/z values that fall within the m/z (ppm) window, then the intensity reported for the EIC for that scan is the **maximum** of all those readings, not the **sum**.

I think that sum makes a lot more sense. The way that this came up now is if you wanted to combine isotopic peaks with the same nominal mass, which may be separated by mass in some samples, but not in others. But setting the ppm window to cover both peaks will still only get you the intensity for one of them.

I don't at the moment see a strong argument for using the maximum, but I'm open to hearing such an argument. Using the maximum results in sort of a simplified centroiding in the case that you have non-centroided data -- I could see how this could be useful if there's a lot of noise in the data. For orbitrap data, this is a complete non-issue. @singleton-christopher I'd be interested to hear if you think it's an issue for TOF data.

@pirman12 @myasteadman please chime in with any thoughts.

**Comment by singleton-christopher** [comment]
Sorry, this got caught in my spam folder, I’ll look at it today.

**Comment by sahil21** [comment]
EIC can be calculated from raw data using a) sum b) average c) maximum of a given slice for each scan. We have to understand how each of these options affects feature detection in various scenarios in MAVEN. So we are planning to add a dropdown in which this three type of EIC representation would be present and the user can choose and experiment with different options. By default, the max option is enabled. This feature will be part of current Sprint 7 (v0.1.2).

A mock-up image with options is below:

![eictype](https://user-images.githubusercontent.com/21240516/26872123-0e486ad6-4b93-11e7-9ed8-019a0d00390a.PNG)

**Comment by chubukov** [comment]
@sahil21 I think this is a pretty advanced setting that would not be commonly changed, so you can hide it in the main options window.

Average would be a pretty nonsensical choice here (stray noisy peak will appear to drastically decrease your signal), so I wouldn't even make that option. As above, sum seems normal to me, but I see the argument for max.

**Comment by sahil21** [comment]
@chubukov 

We have implemented a beta feature to enable the user to select EIC(XIC) calculations based on Max or Sum of Intensity values at a given retention time. By default, Max option will be selected. The option to select EIC Type is there in the Options Dialog. Here is the screenshot for the same:

![image4](https://user-images.githubusercontent.com/21240516/27335656-f0f54c9e-55ea-11e7-8724-b1cf8d3658db.png)


# **Testing for this feature:**

## 1.  Maven Example Dataset (Low resolution data) - Source [maven.princeton.edu](http://genomics-pubs.princeton.edu/mzroll/datasets/exampleProject.zip) 


### **a) PPM Window set at 5 ppm**

**EIC Type: Max, 5 ppm**
![image](https://user-images.githubusercontent.com/21240516/27335817-6a732ae6-55eb-11e7-8210-018b47480506.png)

**EIC Type: Sum, 5 ppm**
![image](https://user-images.githubusercontent.com/21240516/27336044-03e99534-55ec-11e7-84d9-53ca6dc4e5c3.png)

**Results:** Intensities are same because there is only one observation (nobs) at a particular retention time (for the given mz delta).


### **b) PPM Window set at 1000 ppm**

**EIC Type: Max, 1000 ppm**
![image](https://user-images.githubusercontent.com/21240516/27336092-2addbc24-55ec-11e7-99d1-2688d4a1dbb8.png)

**EIC Type: Sum, 1000 ppm**
![image](https://user-images.githubusercontent.com/21240516/27336105-369cbc86-55ec-11e7-98b9-525ebc74e824.png)

**Results:**  Intensities has changed but not significantly even for 1000 pm.


### **c) PPM Window set at 10000 ppm**

**EIC Type: Max, 10000 ppm**
![image](https://user-images.githubusercontent.com/21240516/27336150-50622dd6-55ec-11e7-8a78-109324bbeb65.png)

**EIC Type: Sum, 10000 ppm**
![image](https://user-images.githubusercontent.com/21240516/27336201-7584fcd8-55ec-11e7-9e2a-7ab75900665b.png)

**Results:** Intensities has changed a lot for both the option with 10000 ppm. There are more than 1 nobs at every retention time.


### **d) Peak Detection with reference database**

- **At 10 PPM**

**196 Groups Found with Max EIC Type with 10 PPM**
![image](https://user-images.githubusercontent.com/21240516/27336368-f4beea86-55ec-11e7-8538-d2395d19ba6c.png)

**195 Groups Found with Sum EIC Type with 10 PPM**
![image](https://user-images.githubusercontent.com/21240516/27336374-fa5faf52-55ec-11e7-8093-484f9976b686.png)

**Results:** Groups found are almost the same because EIC has not been changed for 10 PPM.


- **At 100 PPM**

**451 Groups Found with Max EIC Type with 100 PPM**
![image](https://user-images.githubusercontent.com/21240516/27336419-217db3fe-55ed-11e7-876f-fd44bd844f59.png)

**504 Groups Found with Sum EIC Type with 100 PPM**
![image](https://user-images.githubusercontent.com/21240516/27336430-278ff8b0-55ed-11e7-84ed-dfad085cdb9b.png)

**Results:** There is an increase in groups at 100 PPM.



## 2. High-Resolution Data

### a) **PPM Window set at 10 ppm**

**EIC Type: Max, 10 ppm**
![image](https://user-images.githubusercontent.com/21240516/27336563-943c6124-55ed-11e7-9fdc-1fd443d1aaaa.png)

**EIC Type: Sum, 10 ppm**
![image](https://user-images.githubusercontent.com/21240516/27336569-9bcb2ab0-55ed-11e7-9e5d-4c85acf90a46.png)

**Results:** Some intensities have changed.

### b) **PPM Window set at 30 ppm**

**EIC Type: Max, 30 ppm**
![image](https://user-images.githubusercontent.com/21240516/27336604-b4a41ff6-55ed-11e7-8709-3e7a8dd03e71.png)

**EIC Type: Sum, 30 ppm**
![image](https://user-images.githubusercontent.com/21240516/27336613-b9c2ea3a-55ed-11e7-93ce-502b3fc432db.png)

**Results:** Intensities have changed a lot. The number of observations at every RTs is greater than one.

**Comment by chubukov** [comment]
@sahil21 I believe this feature is mostly working as intended. I noticed that when "Sum" is chosen, the EIC mz value at each timepoint is being calculated as the average of all nonzero mzs in the window. I think that something like a weighted average (weighted by intensity) would make more sense.

**Comment by sahil21** [comment]
@chubukov Agreed. Weighted average makes more sense. We'll add this as a new issue.
