### ISSUE TITLE
What is Dotted Area On EIC?

### ISSUE THREAD

**Issue by sp-eldata** [ElucidataInc/ElMaven#202]
While peak picking through a dataset, I saw the EIC attached here. What does the dotted area represent? 
<img width="882" alt="eic-dottedarea" src="https://cloud.githubusercontent.com/assets/22666033/24867550/253a5f46-1e2b-11e7-9b5a-e9b9dc578e4e.png">

**Comment by chubukov** [comment]
This was the old way of representing the baseline. I changed it in #201 . Also, it looks like your baseline is covering the peak, so you probably want to raise the "drop top X% of intensities from baseline" parameter.

**Comment by chubukov** [comment]
Note that if you were using AreaTop, it would not have any effect on the calculation. In current version, only Area gets baseline subtracted.

**Comment by sp-eldata** [comment]
So does this mean that I am using an older version of the tool? Have there been critical updates after this? My version is v0.1.0-beta-7.

**Comment by sahil21** [comment]
@sp-eldata You are using current develop branch. The code change by @chubukov hasn't been merged to develop yet. If you want to use that part, checkout to branch "fix_baseline" and recompile the tool again.

**Comment by sp-eldata** [comment]
@chubukov: Just wanted to understand why are you suggesting to raise the "drop top X% of intensities from baseline" parameter? Will it decrease the number of bad peaks that I have to evaluate?

**Comment by suresh-surampudi** [comment]
@sp-eldata  what probably @chubukov  means is that data has large number of points with high intensity (peak). From the manual, the way I understand is, base line correction is after removing certain % of (default 20) peak intensities. If they are more, your base line will be up. Hence increase the % intensities to be removed, before correcting for baseline. Correct me if I am incorrect @chubukov

**Comment by chubukov** [comment]
![image](https://cloud.githubusercontent.com/assets/13080968/25138364/54d80cb4-2428-11e7-870a-46ab03829888.png)

To properly calculate a peak area (or height) you want to take into account the baseline intensity, otherwise you will have an inflated number. Calculating the baseline (which is due to noise from other low intensity ions) is actually not a completely trivial task and you can imagine fairly complex algorithms.

What Maven does is a simple heuristic.

1. take the entire EIC chromatogram.
2. (The drop topX step): find the (100-X)th percentile intensity, and set anything above it to the value of the (100-X)th percentile.
3. Run a simple smoothing (baseline smoothing window parameter is used here).

- If X=0 then the baseline will be just the (smoothed) chromatogram, so you will very badly underestimate your peaks. That's what's happening in your case -- your "baseline" is halfway up your peaks. (In fact Maven won't let you set X=0, it goes to 1% if you set 0).
- If X=100 then the baseline will be zero, so you will overestimate your peaks.
