### ISSUE TITLE
make parameters more consistent, both for UI and code structure

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#217]
The split between which parameters are set in the peak finding window and which ones are set in the main options is confusing. While working on #210 I was surprised to find that the baseline parameters (dropTopX and smoothingWindow) are actually set in two different places and are completely separate.  In fact, what was happening was that one set of parameters was being used for manual integration of the parent peak, but the other set was used for the isotopic children. For the UI, you can see inconsistencies/confusion reported in #191 also.

Can we make this more consistent? I think that parameters related to how maven picks peaks, groups peaks, or calculates intensities should be in the main options. Parameters specifically related to the automatic search functionality (such as filtering options) should be in the peaks dialog.

And at the same time, can we make the code consistent, so that the `mavenParameters` object contains what one would expect?

**Comment by shubhra-agrawal** [comment]
@chubukov 
We are looking for duplicated parameters between the Options and Peak Detection dialogs. These parameters will be synced

**Comment by chubukov** [comment]
@sahil21 @shubhra-agrawal Lots of activity on this, which is great -- looking forward to seeing the revised interface.

This is really super low priority, but maybe when you've finalized the dialog box layout, it would be cool if you could make sure the tab order of the text boxes is reasonable. It's usually convenient to use the keyboard to change a bunch of settings quickly, and in the current version that I'm using the tab order is so random that it's hard to do.

**Comment by shubhra-agrawal** [comment]
@chubukov 
Here are the changes made for this issue:

- Parameters for EIC Processing and Baseline Calculation lie solely in the Options dialog now. 
- Group Rank tab has also been moved from Peak Detection to Options dialog. 
![grouprank](https://user-images.githubusercontent.com/28925846/28219851-10c8a7ac-68db-11e7-8377-a623457a6fa7.png)

- There is a Consider Retention Time checkbox in the Group Rank tab to enable/disable the deltaRT Weight slider and change the formula for Group Rank
- Match RT checkbox in Peak Detection is no longer connected to Group Rank calculation
- Sliders have been added for Quantile Filters in Peak Detection dialog instead of text boxes

Yes, the tab order is quite random at the moment. We'll fix this and issue #276 as soon as possible and merge it to develop.

**Comment by shubhra-agrawal** [comment]
@chubukov The tab order has been fixed for:
- Peaks dialog
- Alignment dialog
- Options dialog

Summarizing all the changes made in this thread:
- Duplicate instances of parameters have been removed
- All universal parameters have been moved to the Options dialog
- Peaks Dialog only contains parameters used for Automated peak detection
- Tab order has been fixed
- All members of mavenParameters are read in from a single source and updated every time a parameter value is changed in the GUI. The flow of information from settings to mavenParameters will be better handled while working on #425 

Let us know if there are any other changes required as part of this issue. If not, let's close

**Comment by chubukov** [comment]
@shubhra-agrawal the only thing I would add (and this can be a separate issue) is to see if the `MavenParameters` object also conforms to the modular logic.

Thanks!

**Comment by shubhra-agrawal** [comment]
@chubukov MavenParameters is not exactly modular at the moment. We're planning to restructure the code as part of #425. We'll be opening sub-issues for it soon.
