### ISSUE TITLE
Incorrect assignment of names to SRMs in LC MS/MS

### ISSUE THREAD

**Issue by shefalilathwal** [ElucidataInc/ElMaven#260]
In LC-MS/MS data, El-MAVEN is not using retention time information from compound database file to assign fragment names to metabolites. Therefore, different metabolite fragments with same mass but different retention times are not identified correctly. For example, in the SRM list, if there are two transitions with Q1=90, and Q3=90, they should be annotated as pyruvate or lactate based on retention time, but they both appear as pyruvate90/90 right now.

**Comment by r-el-maya** [comment]
In MS/MS dataset, each SRM is assigned to a compound from the compound database.
Present formula to find the closeness of a particular SRM with an i-th compound in the database is:

        dist = √(a^2+b^2)
where,
a = difference in precurzorMz
b = difference in precurzorMz

Thus SRMs with same precursor and product mz but different RT, are categorized wrongly. For example “In the SRM list, if there are two transitions with Q1=90, and Q3=90, they should be annotated as pyruvate or lactate based on retention time, but they both appear as pyruvate90/90 right now.”

In this sprint we plan to incorporate an RT as a deciding parameter as well, essentially :

        dist = √(a^2+b^2+ c^2)
where,
       c = difference in rt value
Adding the RT to the calculation will be an optional parameter. For which, we will have to add a check box to the SRM Widget.
![screenshot from 2017-06-23 16-18-35](https://user-images.githubusercontent.com/29450255/27481679-6d5d307e-583b-11e7-8c02-a445c80ff035.png)

**Comment by r-el-maya** [comment]
@shefalilathwal @sahil21 @chubukov 
We are not using the following formula
    dist = √(a^2+b^2+c^2)
where,
a = difference in precurzorMz
b = difference in precurzorMz
c = difference in rt value
Because, 'a' and 'b' represent different physical entity as that of 'c' thus, summing their squares as if they are of same order is the last that we would want to do. It was a mistake on my part not to work on this on before hand.

Instead we can just check for rt, only for a case where 'dist' is same for two compounds.
i.e., if √(a^2+b^2) value for two or more compounds, we would then and only then check for the rt.

This has been merged to the develop.

**Comment by r-el-maya** [comment]
@shefalilathwal @sahil21 @chubukov 
We are not using the following formula
    `dist = √(a^2+b^2+c^2)`
where,
a = difference in precurzorMz
b = difference in precurzorMz
c = difference in rt value
Because, 'a' and 'b' represent different physical entity as that of 'c' thus, summing their squares as if they are of same order is the last that we would want to do. It was a mistake on my part not to work on this on before hand.

Instead we can just check for rt, only for a case where 'dist' is same for two compounds.
i.e., if √(a^2+b^2) value for two or more compounds, we would then and only then check for the rt.

This change has been merged into the develop branch.
