### ISSUE TITLE
Having to double click to change set name is unintuitive

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#28]

**Comment by GeorgeSabu** [comment]
@sahil21 Can you please describe this a little more?

**Comment by chubukov** [comment]
This is a really trivial thing. It has to do with changing the set that each sample is assigned to ("A" by default). Currently you do this by double clicking on the "A" and entering a new value. Once you know this, it's no problem. But I couldn't figure out for a while because it looked like one of those boxes where should be able to single click and immediately start typing.
