### ISSUE TITLE
deleted peaks causing crash

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#4]
Bookmarking a peak and then deleting it seems to cause a whole host of issues.
1. Group ID of next peak is not set correctly (e.g. bookmark 1,2,3 then delete 2, next peak picked gets 3)
2. After peak is deleted, often get crash as you move between compounds.

**Comment by GeorgeSabu** [comment]
@chubukov we will look into this problem as soon as possible.

**Comment by GeorgeSabu** [comment]
@chubukov This is how I am able to recreate the crash. 
1) Load the files
2) Mark a peaks as good or bad by moving through the compound database list.
3) Then delete all the peaks one by one.
4) Then you hover of the peak that is deleted last then it crashes.

Is this what you saw?

**Comment by chubukov** [comment]
@GeorgeSabu Yes, that is a reproducible way to get the crash.

But it's clear that somehow the information is not getting properly deleted. Firstly, the weird groupID numbering. Secondly, Maven tries to prevent you from integrating the same peak twice (by matching mz and rt). But if you delete the peak and then try to reintegrate it, it still won't be inserted into the table. But if you integrate another one, then you can go back and redo the first one. So somehow the last entry is not being properly cleared.

**Comment by GeorgeSabu** [comment]
@chubukov Crash problem is resolved. We have also changed the way in which "groupid" is assigned. Now, "groupid" will be reordered when peaks are deleted. The problem was **not** related to data not getting cleared properly. After deleting the last peak from the peak table the EIC plot was not getting replotted. So the information related to that particular EIC plot was not present so the application crashed.

**Comment by GeorgeSabu** [comment]
@chubukov This is resolved in the commit [#2b02cca.](https://github.com/ElucidataInc/ElMaven/commit/2b02cca9e000c5746247c83d56a5288d6b7dd543)
