### ISSUE TITLE
Annotation in SRM List for full ms2

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#421]
![image](https://user-images.githubusercontent.com/21240516/31265039-58d8d5e4-aa8a-11e7-87fa-c689071aa4f9.png)

It is using just the precursor m/z to annotate and ignoring the product m/z range.

**Comment by sahil21** [comment]
@chubukov @shefalilathwal I can only think of MRM dataset in which annotation makes sense. Is there any specific case/dataset where it might be needed?

**Comment by shefalilathwal** [comment]
@sahil, I am not sure I follow your comment.

**Comment by sahil21** [comment]
@shefalilathwal Does it makes sense to annotate a filterline(srm Id) just on the basis of precursor m/z? 

For example, it will definitely fail if you have two different compounds in the compound database with same precursor but different product m/z. I think no annotation is better than wrong annotation.

**Comment by chubukov** [comment]
I don't really use the link-based workflow (I'm going to not annotation because it has other meanings) so it's been a little hard for me to understand some of these issues. But I would point out that essentially these two functions 

1. linking all compounds to matching srmIds
2. doing automatic compoundDb search on ms/ms data

are pretty much the exact same thing. They both take some information about the compound (precursorMz, productMz, collisionEnergy(maybe), and expectedRt) and try to find the proper EIC, from the correct scan type/transition.

So I would try to make them use the exact same workflow/functions, regardless of whether you have true triple quad MRM data, or some kind of pseudo-MRM, or some other type of data.

**Comment by chubukov** [comment]
@sahil21 ok actually I may have partially misunderstood this.

I can definitely see a case where you would want to select a scan just based on precursorMz. If you knew the parent mass and wanted to see the entire fragmentation spectrum, you would do exactly this. What I think Maven should do in this case is show you the MS1 chromatogram, and then have the option of seeing the MS2 spectra by clicking around.

**Comment by shubhra-agrawal** [comment]
@sahil21 Selecting 209/121 from the ligand widget pulls up the whole 209->[50-230] scan.
![annotation](https://user-images.githubusercontent.com/28925846/31501772-cdeb601a-af88-11e7-9303-ae5b89bd5178.png)

**Comment by saifulbkhan** [comment]
I do not think filterlines are linked to compounds anymore. Assuming that was the original issue, closing this.
