### ISSUE TITLE
deleted samples

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#5]
1. bookmark a peak
2. delete one or more of the samples
3. click on the peak in the bookmarks table

This causes a crash. Probably the right behavior is to delete the entries in the peak table corresponding to that sample, but a temporarily acceptable alternative is to force the user to delete all the tables.

**Comment by GeorgeSabu** [comment]
@chubukov might be deleting all peaks is not deleting all the related information. We will look into this as soon as possible.

**Comment by chubukov** [comment]
Just to clarify, here I'm talking about deleting a sample (i.e. a data file). One of the other issues was regarding deleting peaks from the table.

**Comment by GeorgeSabu** [comment]
@chubukov I am not able to reproduce the crash that you pointed out. We tried to reproduce it on both windows and ubuntu.

While integrating the peaks I guess you deselected some of the samples so that the integration happens only for the selected samples. And the samples that you would deselect depends on the peak that you want to integrate. Is this the general way users integrate peaks?

In the above scenario, I guess deleting samples should delete peaks which contain those samples from bookmarks table. If we just make this change then it means that in the automatic peak detection if any of the samples are deleted all the peaks will be deleted because both of them are derived from the same class.

On the same note if a peak from the bookmark table is selected then only the samples that are used for peak integration should be selected right?

**Comment by chubukov** [comment]
@GeorgeSabu Ok,it's a little weird, I admit that it only happens for some peaks and not for others.

I put a video up on dropbox (Maven/bug_reports/2016_10_26_deleted_samples). But I can do the same for other peaks and it works fine. Maybe something to do with the zero scans bug again?

**Comment by chubukov** [comment]
@GeorgeSabu Regarding your other question -- no, I wasn't only selecting certain samples. I think in that case it would be very reasonable to set the intensity for the unselected samples to zero. That's not the way we usually do things, but I could see someone doing that. 

You raise a bunch of good points though -- like what happens if you deselect, integrate, reselect and the go to the bookmarked peak. I guess currently you would get a reintegration that doesn't match the values in the table? That seems acceptable to me for the time being.

Ideally deleting samples should not delete any of the peaks from the bookmark table. But I would be sort of ok with saying "if you delete a sample, you delete all bookmarked peaks" -- that would surely be easy to implement and save some headaches.

**Comment by chubukov** [comment]
@GeorgeSabu Actually, the reintegration not matching the value in the peaks table already can happen easily even without the sample deselection. E.g. bookmark a peak, then change the ppm window. The displayed EIC will not match what's in the bookmarked table. So I guess we should accept this behavior.

I guess one useful thing would be to store the parameters used for integration with each bookmarked peak. So if one metabolite was integrated with a 10ppm window and another with a 15ppm window, you would store that information, and could output it somehow. That seems like a pretty major refactor.

**Comment by GeorgeSabu** [comment]
@chubukov I am still not able to reproduce the crash I tried it with both window and ubuntu. Would this be some artifact due to settings that El-maven is given? Can you share with me the settings and also the compound database used for this?

**Comment by GeorgeSabu** [comment]
@chubukov "if you delete a sample, you delete all bookmarked peaks" this feature we want only because of the crash right? After we delete a sample if the application does not crash then we are good, right? 

While peak integration code does not keep samples that are used for integration in memory. So deleting sample should not be directly related to crash. And also if the user wants to save .csv with and without some samples deselected we shouldn't delete bookmarked peaks right?

**Comment by GeorgeSabu** [comment]
@chubukov We were able to reproduce the error steps:
The exact step that is demonstrated in the video. But isotopes widget should be enabled, if not crash does not happen. This crash happens in all versions of maven.

**Comment by sabsgeo** [comment]
@chubukov This problem is been resolved. The problem was while clicking on a peak or marking peak as good or bad scan information is stored in the isotopic widget. Now when we delete the sample from which scan information is collected, scan information in the isotopic widget is getting corrupted. Because the sample doesn't exist anymore it's getting garbage values for the scan which is causing the application to crash. 

We resolved this by clearing the scan information after its use.

**Comment by sabsgeo** [comment]
@chubukov This also means that there is some problem in the way samples are been deleted. Which I will add as another issue and follow up separately.
