### ISSUE TITLE
Red dashed RT line does not get removed when selecing a compound that has no RT specified

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#553]
Selecting a compound with no RT value (empty field in the CSV file), the RT line in the main window remains at the position it was drawn from the last compound with an RT value. Also, the position and zoon of the main window remains the same. Instead, the RT line should be removed and the main window should zoom to either the best peak group in the m/z window or zoom all the way out (not sure which is better, lean toward zoom out).

**Comment by shubhra-agrawal** [comment]
@lparsons We've merged a fix for this to develop. When there is no expected Rt information, the Rt line is removed and the window is zoomed out.

There is a corner case here which I'm not able to cover right now. When I upload _MS2 data_, select a metabolite with _no_ expected Rt information, which has an _empty EIC_, the window goes completely blank. There is no title, plot axes etc. This is confusing because the user would not know if there really is no EIC or if there's a bug and they just can't see it. Seems to work for all other possibilities. 

I'm pushing this as a hot-fix for now. Not closing this issue till this corner case is covered.

**Comment by lparsons** [comment]
@shubhra-agrawal I'm not seeing this fix in the latest develop build (`El_Maven_v0.2.4-beta-8-g85d15c8`).
![image](https://user-images.githubusercontent.com/645128/35739891-1e83c91a-0801-11e8-812e-922f93b922db.png)

**Comment by shubhra-agrawal** [comment]
@lparsons There was a file version mix up on my end. Apologies for that.

I have implemented a fix that covers the above mentioned corner case. If there is no expected Rt, the EIC will zoom all the way out and the Rt line will be removed. Even in the case of empty EIC. This has been merged to develop.
