### ISSUE TITLE
New baseline Algorithm

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#583]
There are a couple of challenges with current baseline algorithm:
1. The baseline calculated by El-MAVEN is often 'inaccurate'
2. Baseline correction is currently done based on a global setting. We can't set separate baseline for individual compounds/groups (similar to #556)

**Comment by sahil21** [comment]
Key points from the meeting with @chubukov 
- Noise and Baseline should be dealt with the same algorithm
- Validating baseline algorithm is hard - Use simulated data or check visually.

Some of the baseline algorithm we are trying
1. **airPLS algorithm** - https://code.google.com/archive/p/airpls/
2. **IRLS algorithm** - https://cran.r-project.org/web/packages/baseline/baseline.pdf
3. **peakutils baseline** -  http://pythonhosted.org/PeakUtils/index.html

**Comment by sahil21** [comment]
@chubukov We have made a prototype depicting 3 baseline algorithms i.e **airPLS**, **IRLS** and **peakutils baseline**. You can test out the prototype here - [Baseline Prototype - Polly Dash App ](https://polly.elucidata.io/polly-dash?polly-notebook-name=baseline.zip&polly-project-id=52)

About Baseline prototype:
- There are 4 sliders in the dash app (1 each for airPLS and peakutils. There are 2 sliders for IRLS. More information around these algorithms is mentioned in the previous comment)
- You can select multiple algorithms to compare the results
- We have added 5 example EICs to test out the baseline algorithms (Select EICs using drop-down)

Let us know your thoughts around these baseline algorithms. 

PS. We have used [Polly](polly.elucidata.io) just to host the [dash app](https://plot.ly/products/dash/) for easy sharing of analysis. The baseline code will be part of this open source repository.

**Comment by chubukov** [comment]
@sahil21 Super. Really great idea. 

The only algorithm that seems to me to give anything reasonable is IRLS. I got what looks to me like pretty decent behavior at lambda1=4 and lambda2=7. 

Was that your experience as well? Were you able to get anything reasonable out of the other two? If so, at what parameters?

Once we have it narrowed to just a few options to test, let's run it on a much wider variety of EICs?

**Comment by sahil21** [comment]
@chubukov I also found IRLS reasonably better than other two (airPLS & peakutils). 

> Once we have it narrowed to just a few options to test, should we run it on a much wider variety of EICs? There is also the question of computational complexity -- I'm not sure that these iterative fitting algorithms are going to be super snappy in the GUI...

Makes sense. I'll release some beta version of El-MAVEN soon with IRLS baseline correction algorithm. This way we will be sure of the performance of this algorithm.

**Comment by chubukov** [comment]
@sahil21 if you've looked at the core of the algorithm: how big of a window does it use? Is that also a parameter?

**Comment by sp-eldata** [comment]
Sahil/Victor, aren’t we better off first testing it more outside of
El-Maven?

**Comment by sahil21** [comment]
@chubukov 

> how big of a window does it use?
 
Are you referring to the smoothing window here? It doesn't seem like the algorithm is using any window function here. It is doing a global fitting.

@sp-eldata Agreed. That should be the ideal case. But we won't be able to test the performance of the algorithm if we use the prototype.

**Comment by chubukov** [comment]
@sahil21 that's what I was worried about a little bit. That means that potentially you would have very different behavior depending on how large an EIC window you pulled, right? 

My suggestion would be to try a couple tests where you take these same EICs and pad them on either side with a few (5?) minutes of either zeros or some noise that's similar to the noise around the peak, and see how the baseline calculation changes.

Could you link to the actual R code or python code that does the calculation? Perhaps we could think together about performance-conscious implementation.

**Comment by sahil21** [comment]
@chubukov Yes, I think there will be a change in the baseline calculation. But we have to test how drastic it is. I'll update the prototype with the mentioned tests. 

Link to the IRLS R code - https://github.com/cran/baseline/blob/master/R/baseline.irls.R

**Comment by sahil21** [comment]
@chubukov There are other baseline algorithms too in this package - https://github.com/cran/baseline. We can try them out if IRLS doesn't work for us.

**Comment by chubukov** [comment]
@sahil21 took a quick look. I think that with some good linear algebra libraries this code should be pretty fast.

Relating to the test of expanding the baseline out -- maybe an even more interesting variant is what happens when there is a second peak quite far away. Ideally it wouldn't affect the baseline of the first peak very much (?)

**Comment by sahil21** [comment]
@chubukov 

> Relating to the test of expanding the baseline out -- maybe an even more interesting variant is what happens when there is a second peak quite far away. Ideally it wouldn't affect the baseline of the first peak very much (?)

I have put up some test related to this on [Polly Dash](https://polly.elucidata.io/polly-dash?polly-notebook-name=irls.zip&polly-project-id=77). 
Some details of this particular dash app:
1. There is only one baseline algorithm - IRLS
2. There are two EICs (First EIC has two peaks and second EIC is modified version of the first EIC where one peak is being removed)

Some Insights
- Clearly, the baseline is being affected because of the second peak
- The baseline doesn't change if the value of `Lambda 1` is low (in this case it is around 3 or less)

I'll put up some more EICs to test this out.

**Comment by chubukov** [comment]
@sahil even on the version with one peak (EIC2), it looks quite a bit different than the behavior on the first set (I guess EIC 4 from the first set is the most similar)

**Comment by shefalilathwal** [comment]
@chubukov @sahil21 My experience was similar to yours with the three algorithms. IRLS is the one that seems to work reasonably around the settings Victor mentioned earlier.

**Comment by raaisakuk** [comment]
> My suggestion would be to try a couple tests where you take these same EICs and pad them on either side with a few (5?) minutes of either zeros or some noise that's similar to the noise around the peak, and see how the baseline calculation changes.

If I understood you correctly, are you saying something like this?  (drawn in paint, please excuse the horrible drawing)
![image](https://user-images.githubusercontent.com/33527542/36796791-6ba77840-1c74-11e8-8453-9939b4b5196c.png)

Because I think this case was missing in the example EICs. @sahil21 Please correct me if I am wrong.

**Comment by chubukov** [comment]
@raaisakuk The case you've drawn is probably going to be tricky to get exactly right

What I was suggesting was something a little different (and @sahil21 put together something a little bit along these lines). Basically I just wanted to see how sensitive the algorithm was to how much of the EIC consisted of the peak, and how much of baseline. So how different would the baseline be if you had an EIC of a peak surrounded by 1 minute of zeros/noise on either side vs if you extended that out to 2 minutes or more. Or even more interestingly, what if you extended it out and had another peak a few minutes away.

**Comment by sahil21** [comment]
@chubukov 

> even on the version with one peak (EIC2), it looks quite a bit different than the behavior on the first set

At what values are you comparing these? I don't see much difference in the behavior. Could you clarify more on this? Also, just make sure not to use two dash apps simultaneously on the same browser. It is giving some weird behavior. This is happening because of some socket connections.

Also, we have added an upload component to the dash app so that we can test IRLS easily with a couple of EICs. It takes El-MAVEN output json as an input. Here is the [new dash app](https://polly.elucidata.io/polly-dash?polly-notebook-name=upload_baseline.zip&polly-project-id=18). Let us know how it works.

**Comment by LiChenPU** [comment]
@sahil21 
Hi, I test out different algorithms as well. Indeed IRLS gives most reasonable results to all EIC, but I also find AirPLS has some positive features. I like that AirPLS (lambda = 7) can draw baseline between the bottom of a peak, but it is too sensitive to noise. IRLS (lambda1 = 4, lambda2=7 as @chubukov suggested) shows insensitivity to noise. Is it possible to combine the two, around peak area to use AirPLS and across whole spectrum to use IRLS? If have to pick one, IRLS is indeed better.

**Comment by chubukov** [comment]
@sahil21 To me the major sticking point is still that the baseline will change drastically if you add a second peak to the EIC. If you have just one peak then even the current algorithm (drop top X% and then smooth) usually gives a totally reasonable result.

**Comment by sahil21** [comment]
@chubukov @LiChenPU It is clear that we cannot use IRLS algorithm (because of the global fitting issue). I'm testing out some remaining algorithms from the R baseline package - https://github.com/cran/baseline. I'll update the dash prototype if something useful comes up.

**Comment by mayankmtg** [comment]
@chubukov I was giving baseline a look and wanted to understand if we would consider the following baseline as a good one in our mass-spec context.

![screenshot from 2018-06-19 13-41-15](https://user-images.githubusercontent.com/22257816/41585105-b265f398-73c6-11e8-9402-10aed1fd4580.png)

I am just asking about the shape of the baseline. Is it good or bad? This baseline essentially would be responsible for flattening the base and marking peaks and noise based on the ratio of signal and baseline intensity at a particular rt. Tag: @sahil21 @shubhra-agrawal

**Comment by chubukov** [comment]
Looks beautiful to me

**Comment by saifulbkhan** [comment]
We have recently started trying another baseline algorithm - [Asymmetric Least Squares Smoothing](https://zanran_storage.s3.amazonaws.com/www.science.uva.nl/ContentPages/443199618.pdf), which I believe is also what @mayankmtg showed a screenshot of. I also a made a [dash application](http://baseline-dash-app.herokuapp.com) to try it out. The app starts on the example EIC page that is very similar to the apps that @sahil21 originally developed. In addition an EIC with the corrected signal is shown beside.

The "Custom EICs" section (meant to be used for trying out datasets exported from El-MAVEN in JSON format) misbehaves a bit too much when deployed remotely, but seems to work fine when hosted locally (I can provide instructions to run this web app locally if need be).

### Outline of the algorithm:
A light smoothing (small **_λ_** value) algorithm will remove noise while a strong smoothing (large **_λ_** value) one will give a slowly varying trend of the signal. This however does not give us a baseline, since the trend captures deviations in both directions (positive or negative). AsLS (asymmetric least squares) introduces an "asymmetry" (denoted by **_p_**) parameter that can be used to favor only one type of peak -- either positive or negative (as expected from chromatograms obtained from most scientific experiments). Thus, for our purposes, the algorithm uses a variant of the "Whittaker" smoother where positive deviations with respect to baseline are weighted _much_ less in compared to negative ones.

### Advantages of AsLS Smoothing:
- Fast (even for high resolution data).
- Can be tuned using only two parameters (**_λ_** for smoothness and **_p_** for asymmetry)
- Does not suffer from global fitting issue as the previously tested algorithms do.

### Suitable range of parameters:
The app provides two sliders:
1. Smoothness (**_λ_**) for flexibility: This value is represented as a linear scale for log of **_λ_**. In my experience the range (3 ≤ **_λ_** ≤ 7) works well for most of the datasets I was able to try.
2. Asymmetry (**_p_**) for position: The value of p needs to be in the range (0.001 ≤ **_p_** ≤ 0.1) to perform well on positive peak chromatograms. Again, in my experience the range (0.015 ≤ **_p_** ≤ 0.030) was able to capture most of the EIC's baselines.

As a side-note I would suggest that if we are to provide a baseline algorithm we should give users a way to tweak the parameters of the algorithm for each EIC in El-MAVEN, because from what I have seen no set of parameters are good for all EICs. But that does not mean we should not aspire to choose a good default for these two parameters, which partly why I would like you all to try this out and give useful feedback.

FYI: @chubukov @raaisakuk @shefalilathwal @lparsons @surbhipoddar @Raghavdata @LiChenPU

**Comment by mayankmtg** [comment]
@saifulbkhan It was great of you to have shown interest in the same. After I had suggested the algorithm in the above comment I had also implemented the same in the branch feature_baselineCorrection. It is a direct implementation of the Asymmetric Least Squares Smoothing in ElMaven and its results. You can view the same and take references from that as well. As was suggested by @sahil21 and @Raghavdata on the algorithm, perhaps it is not compatible with ElMaven. However I believe that upon fine tuning Smoothness (λ) and Asymmetry (p) parameters, we could get the ideal baseline with minimum peak area cut. Try approximating the values every time for every data-set entered to incorporate the MassSpec data-set variability, and you could have your answer. You could refer to the C++ asLSS implementation repository individually at: 

https://github.com/mayankmtg/MassSpecPeakDetection/blob/master/fixed_bin/asLSS.cpp

**Comment by saifulbkhan** [comment]
@mayankmtg Varying the parameters based on the dataset is a good idea, I think. In fact I felt that the value of lambda and p need to be increased in the given range when the resolution of the EIC is high. We will need more thorough testing on this though to be able to find out how and if there are other aspects of a dataset that can be taken into account for calculating the default parameters.

Also, I am aware of your branch and if we go forward with this algorithm, I will most likely use the implementations there rather than start from scratch.

**Comment by chubukov** [comment]
@saifulbkhan thanks!

Maybe this could be ok with some fine tuning of the parameters. I do like that it's not thrown off by the extra peak added between EIC 6 and EIC 7. 

It does look a little weird to me that at most smoothness values (the non-degenerate ones) you always get this fairly significant rise in the baseline around the peak. That seems to happen at any non-zero `p` value, and is obviously exaggerated at low smoothness values. 

It also seems that when you have a non-zero amount of noise (e.g. EIC 1,2, and 5) it is a little funny looking -- I would normally have expected the baseline to run approximately along the mean of the noise, as in the @mayankmtg example pictured above. With this algorithm, it seems to run along the lower bound of the noise. Maybe that's ok -- it could be totally good enough for most purposes.

So I guess I see some nice points here, but it does look a little funny to me still, at almost any range of parameters.

**Comment by saifulbkhan** [comment]
@chubukov I was not involved with the project when this problem was first being investigated but after doing some quick lookups, I was able to find out the following:

1. XCMS only has a simple baseline estimation built within its peak detection methods (using second derivative of the signal which translates to curvature). An older version of XCMS had a simple threshold feature (same as El-MAVEN), but I'm not sure if its still available. There was a recent [discussion](https://github.com/sneumann/xcms/issues/317) around this on the issue board of xcms3 R package.
2. According to their [documentation](https://ftp.mi.fu-berlin.de/pub/OpenMS/release2.2.0-documentation/html/TOPP_BaselineFilter.html) OpenMS commonly uses a "Top-hat" filter, a tool used in morphological image analysis but seemingly works for any uniformly distributed signal.
3. MZmine2 [offers](https://github.com/mzmine/mzmine2/tree/master/src/main/java/net/sf/mzmine/modules/rawdatamethods/filtering/baselinecorrection/correctors) 5 different baseline correction algorithms which are derived from the same R baseline package from which we have been trying out algorithms from, namely:
    - Asymmetric baseline corrector (very similar and from one of the authors of the AsLS Smoothing algorithm we are trying).
    - Local Minima + LOESS (smoothed low-percentile intensity) baseline corrector (uses [`bslnoff` method](https://bioconductor.org/packages/release/bioc/manuals/PROcess/man/PROcess.pdf#Rfn.bslnoff.1) of PROcess Bioconductor R package).
    - Peak detection baseline corrector [from R package](https://www.rdocumentation.org/packages/baseline/versions/1.2-1/topics/baseline.peakDetection).
    - Rolling ball baseline corrector [from R package](https://rdrr.io/cran/baseline/man/baseline.rollingBall.html).
    - Rubber band corrector [from R package](https://cran.r-project.org/web/packages/hyperSpec/vignettes/baseline.pdf#section.3)

Apart from these there's another [webpage](http://strimmerlab.org/notes/mass-spectrometry.html) (although I cannot speak for its correctness) which seems to keep a track of what different R packages offer for MS analysis.

Hope this helps.

**Comment by Raghavdata** [comment]
@chubukov Following up from Saiful's conversation do you think that the new baseline algorithm is covering more corner cases than the present algorithm in El-MAVEN? If yes, then do you think we should implement this in the next release of El-MAVEN as a beta feature to test it out further on larger datasets? (The default option will still be El-MAVEN's present baseline algo)

Let us know what you think, we are planning the next release of El-MAVEN (version 0.6, expected end of November) and would like to incorporate this if you approve.

Awaiting your reply

**Comment by chubukov** [comment]
@Raghavdata Yes, I believe it is clearly an improvement over the current algorithm. If you think that it's reasonably straightforward to implement, then I would be in favor. 

Have we tried some version of tophat?

**Comment by saifulbkhan** [comment]
We have shipped AsLS Smoothing in release v0.6.1 and have beein trying out Top-hat in a prototype. More details on this will be added soon

**Comment by saifulbkhan** [comment]
I am going to go ahead and close this long-standing issue. The two algorithms should work for the majority of chromatographic data and are quite performant as well. Any other improvements can be discussed separately.
