### ISSUE TITLE
Option box does not plot updated EIC realtime

### ISSUE THREAD

**Issue by omkarap55** [ElucidataInc/ElMaven#770]
Describe the bug
If user tries to change grouping parameters, updated EIC is not visible to user. User sees previous EIC only. To see updated EIC user has to select different compound and then select the original compound, then only changes are reflected in EIC. 

To Reproduce
1. Find peaks
2. From Options, change grouping parameters.
3. Perform step 2 3-4 times and observe whether EIC changes or not

Expected behavior
As soon as the user changes the grouping parameters, updated EIC should be plotted.

**Comment by chubukov** [comment]
Exactly the same thing happens with changing the baseline parameters, and it's particularly misleading because the baseline does get redrawn on top of the peaks (but still using the old settings).

As far as I remember, this behavior is new -- I think older versions redrew the EIC immediately.

@sahil21 @shubhra-agrawal

**Comment by saifulbkhan** [comment]
The EIC will now be updated whenever any of the baseline parameters are changed. Closing this issue and opening a new one for the issue where the baseline is drawn behind the chromatogram making it harder to see.
