### ISSUE TITLE
feature request: select and delete button should delete multiple entries in table

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#8]
If you select multiple entries in a peaks table and then hit the delete key, it will still only delete the first entry.

Maybe there should also be a "delete" entry in the right-click context menu (right now there is only "delete all").

**Comment by chubukov** [comment]
appears to be fixed

**Comment by GeorgeSabu** [comment]
@chubukov We haven't modified the deleting code. What we have done is that we wrote a for...loop around the already existing Delete function and updated the function name. 
Some of the reasons I understood why this is slow are:
1) After each deletion, the table is getting updated. If we do the update, in the end, it will save some time. But this is not the major reason why it's slow.
2) After each entry is deleted because of this statement `connect(treeWidget, SIGNAL(itemSelectionChanged()),SLOT(showSelectedGroup()));` baseline, EIC, spectral computation all is happening. This is the one which is consuming the most of the time.
3) Because deletion of the group happens on the same thread as a GUI. GUI is getting unresponsive if the number of groups that is deleted is little large like > ~100. So making this into a different thread also would help.

This would come under GUI architectural changes. There will be much more changes like this that would be there which will make the GUI and general user experience better. So It's better to take it under the GUI architectural sprint which we would like to do next.

**Comment by chubukov** [comment]
@GeorgeSabu that sounds fine to me.
