### ISSUE TITLE
Prompt user to enter a database in CLI

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#847]
Peak detection in CLI cannot work without a database file, which makes it a required parameter. User should be prompted to enter a database file if it is not provided.

**Comment by saifulbkhan** [comment]
@chubukov We are not making any changes to our CLI tool that would make it interactive in the "prompt user for input" sense. This issue was most likely referring to the absence of a warning to the user when they are trying to do a targeted analysis but have not provided a compound's DB.

This issue should now be resolved since #860 and #863 were merged.
