### ISSUE TITLE
Maven crashing when selecting additional metabolites after intial integration

### ISSUE THREAD

**Issue by singleton-christopher** [ElucidataInc/ElMaven#87]
I was using Maven (El_Maven_2016_12_19) and had loaded in files from both D:\Data\LCQTOF\IEM Exploratory\[edited]\A3010 and D:\Data\QE2\IEM\[edited]\A3019 but the program kept crashing.  I had loaded in all .mzxml files and peak-picked [edited] using the values from the [edited] list of metabolites located in Y:\Metabolomics\Maven Source Files\QTOF   I then tried to select [edited], and as soon as I clicked on <edited> the program crashed.  This happened several times, and I had to restart each time.

**Comment by chubukov** [comment]
Comment edited to remove confidential info -- maybe we have to make this repo private after all.

**Comment by singleton-christopher** [comment]
Good catch, sorry, I thought the thread was private.  I’ll edit before posting next time.

**Comment by chubukov** [comment]
Our fault, we should have some way to deal with this. Thanks for posting the report!

**Comment by chubukov** [comment]
@GeorgeSabu I can reproduce that this consistently crashes. I made a new folder in the dropbox with some example files and a source file. I don't see any error message in the console.

**Comment by chubukov** [comment]
@singleton-christopher @GeorgeSabu I just tried doing some more debugging on this. Chris, one workaround for now would be to simply make a source file of only the metabolites you're interested in and then do automated peak picking. As long as I don't click on the peak in the EIC window, I'm able to avoid crashes.

Some notes:
a) if I enter the m/z in the top right to get the EIC instead of selecting it from the compound widget, then I am able to click on the peak without it crashing. However, if I then try to bookmark the peak with either doubleclick or shift-drag, nothing seems to happen (bookmarks table does not get populated).

b) automated peak selection works fine. However, scrolling through the table and then clicking on the peak creates the same crash as before.

**Comment by chubukov** [comment]
@singleton-christopher sabu and i were just playing with this. try it with the isotope barplot disabled. seems to work ok for now.

**Comment by GeorgeSabu** [comment]
@chubukov @singleton-christopher I have fixed this issue in the latest develop.

**Comment by GeorgeSabu** [comment]
@chubukov We have resolved "bookmark the group with no compound name annotated with either doubleclick or shift-drag," in the develop branch. Which you have mentioned in this issue.

**Comment by chubukov** [comment]
Closing this -- bug that was causing the crash was found and resolved. Please create a new issue if you experience other crashes.
