### ISSUE TITLE
compound search widget is too sensitive to hover over spectrum widget

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#888]
Run a search in the compound search widget. Move the mouse out of the widget, passing over the spectrum widget. The compound search widget will respond to any hover over any m/z peak, resetting the state.

Even as a feature, this isn't great, since even if you wanted to select something from the spectrum widget, you'd have to figure out how to get your mouse out of it without hovering on anything else.

But if you have both widgets open, it makes using the search widget amazingly frustrating.

Not sure if it happens only with the spectrum widget or perhaps other ones as well.

**Comment by shubhra-agrawal** [comment]
I tried it for the first time and yes. It's virtually impossible to use
both together. Even if I dock one widget beside the compound db.

Are there any advantages to the hover mechanism here? (I've never used the
compound match widget much) If not, we can change the behavior to make it
react to clicks instead of a hover. Like it works for the EIC widget.

**Comment by saifulbkhan** [comment]
With release v0.8.0, the compound search widget now only updates when a peak in spectra widget is _clicked_. Using it should no longer be frustrating.
