### ISSUE TITLE
Crash after changing PPM cutoff setting

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#918]
**Describe the bug**
ElMaven crashes (sometimes, but not infrequently) when the PPM is changed and a peak is clicked.

**To Reproduce**
1. Open some sample data
2. Click on a peak
3. Change the `ppm` cutoff
4. Click on the peak again 
5. ElMaven crashes and offers to send a report

**Expected behavior**
ElMaven to show the updated peak data

**System (please complete the following information):**
 - Ubuntu v0.5.0, Windows v0.4.0

**Comment by shubhra-agrawal** [comment]
@lparsons Thanks for reporting the steps! I can see the crash on my system. Some further observations:
- Only happens when I decrease the ppm (in my limited testing)
- Only happens when the isotope widget is open 

It's probably some corner case from the isotope widget considering the crash only happens on clicking on the peak (which is when the isoWidget is updated). IsoWidget is also a sample-centric widget so if decreasing the ppm negatively affects the selected peak, it might not know how to deal with the suddenly missing peak.

**Comment by shubhra-agrawal** [comment]
@lparsons This has been fixed and merged to develop. Will be part of the v0.7.0 release.
